import 'dotenv/config';

export const ENV = {
  HOST: process.env.HOST!,
  API_GATEWAY_NAME: process.env.API_GATEWAY_NAME!,
  AUTH_SERVICE_NAME: process.env.AUTH_SERVICE_NAME!,
  USER_SERVICE_NAME: process.env.USER_SERVICE_NAME!,
  EVENT_SERVICE_NAME: process.env.EVENT_SERVICE_NAME!,
  TICKET_SERVICE_NAME: process.env.TICKET_SERVICE_NAME!,
  PAYMENT_SERVICE_NAME: process.env.PAYMENT_SERVICE_NAME!,
  NOTIFICATION_SERVICE_NAME: process.env.NOTIFICATION_SERVICE_NAME!,
  API_GATEWAY_PORT: +process.env.API_GATEWAY_PORT!,
  AUTH_SERVICE_PORT: +process.env.AUTH_SERVICE_PORT!,
  USER_SERVICE_PORT: +process.env.USER_SERVICE_PORT!,
  EVENT_SERVICE_PORT: +process.env.EVENT_SERVICE_PORT!,
  TICKET_SERVICE_PORT: +process.env.TICKET_SERVICE_PORT!,
  PAYMENT_SERVICE_PORT: +process.env.PAYMENT_SERVICE_PORT!,
  NOTIFICATION_SERVICE_PORT: +process.env.NOTIFICATION_SERVICE_PORT!,
  DATABASE_URL: process.env.DATABASE_URL!,
};
