import 'dotenv/config';

export const ENV = {
  HOST: process.env.HOST!,
  API_GATEWAY_NAME: process.env.API_GATEWAY_NAME!,
  AUTH_SERVICE_NAME: process.env.AUTH_SERVICE_NAME!,
  USER_SERVICE_NAME: process.env.USER_SERVICE_NAME!,
  EVENT_SERVICE_NAME: process.env.EVENT_SERVICE_NAME!,
  TICKET_SERVICE_NAME: process.env.TICKET_SERVICE_NAME!,
  PAYMENT_SERVICE_NAME: process.env.PAYMENT_SERVICE_NAME!,
  NOTIFICATION_SERVICE_NAME: process.env.NOTIFICATION_SERVICE_NAME!,
  API_GATEWAY: +process.env.API_GATEWAY!,
  AUTH_SERVICE: +process.env.AUTH_SERVICE!,
  USER_SERVICE: +process.env.USER_SERVICE!,
  EVENT_SERVICE: +process.env.EVENT_SERVICE!,
  TICKET_SERVICE: +process.env.TICKET_SERVICE!,
  PAYMENT_SERVICE: +process.env.PAYMENT_SERVICE!,
  NOTIFICATION_SERVICE: +process.env.NOTIFICATION_SERVICE!,
  DATABASE_URL: process.env.DATABASE_URL!,
};
