import 'dotenv/config';

export const ENV: {
  HOST: string;
  API_GATEWAY_NAME: string;
  AUTH_SERVICE_NAME: string;
  USER_SERVICE_NAME: string;
  EVENT_SERVICE_NAME: string;
  TICKET_SERVICE_NAME: string;
  PAYMENT_SERVICE_NAME: string;
  NOTIFICATION_SERVICE_NAME: string;
  API_GATEWAY_PORT: number;
  AUTH_SERVICE_PORT: number;
  USER_SERVICE_PORT: number;
  EVENT_SERVICE_PORT: number;
  TICKET_SERVICE_PORT: number;
  PAYMENT_SERVICE_PORT: number;
  NOTIFICATION_SERVICE_PORT: number;
  DATABASE_URL: string;
  ACCESS_TOKEN_SECRET: string;
  ACCESS_TOKEN_SECRET_EXP: number;
  PRODUCTION_MODE: boolean;
} = {
  HOST: process.env.HOST!,
  API_GATEWAY_NAME: process.env.API_GATEWAY_NAME!,
  AUTH_SERVICE_NAME: process.env.AUTH_SERVICE_NAME!,
  USER_SERVICE_NAME: process.env.USER_SERVICE_NAME!,
  EVENT_SERVICE_NAME: process.env.EVENT_SERVICE_NAME!,
  TICKET_SERVICE_NAME: process.env.TICKET_SERVICE_NAME!,
  PAYMENT_SERVICE_NAME: process.env.PAYMENT_SERVICE_NAME!,
  NOTIFICATION_SERVICE_NAME: process.env.NOTIFICATION_SERVICE_NAME!,
  API_GATEWAY_PORT: +process.env.API_GATEWAY_PORT!,
  AUTH_SERVICE_PORT: +process.env.AUTH_SERVICE_PORT!,
  USER_SERVICE_PORT: +process.env.USER_SERVICE_PORT!,
  EVENT_SERVICE_PORT: +process.env.EVENT_SERVICE_PORT!,
  TICKET_SERVICE_PORT: +process.env.TICKET_SERVICE_PORT!,
  PAYMENT_SERVICE_PORT: +process.env.PAYMENT_SERVICE_PORT!,
  NOTIFICATION_SERVICE_PORT: +process.env.NOTIFICATION_SERVICE_PORT!,
  DATABASE_URL: process.env.DATABASE_URL!,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET!,
  PRODUCTION_MODE: Boolean(process.env.PRODUCTION_MODE !== 'false'),
  ACCESS_TOKEN_SECRET_EXP: +process.env.ACCESS_TOKEN_SECRET_EXP!,
};
